repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        language: system
        entry: pnpm exec eslint .
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
      - id: prettier-check
        name: prettier check
        language: system
        entry: pnpm exec prettier --check .
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
      - id: knip
        name: knip
        language: system
        entry: pnpm exec knip
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
