name: commitlint

on:
  pull_request:

jobs:
  commitlint:
    runs-on:
      - self-hosted
      - Linux
      - X64
      - markolo-hetzner
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.cjs
